"use client";

import React, { createContext, useContext, useState, useEffect } from 'react';

type Language = 'en' | 'am';

interface LanguageContextType {
    language: Language;
    setLanguage: (lang: Language) => void;
    t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
    en: {
        dashboard: "Dashboard",
        queue: "Request Queue",
        revenue: "Revenue Journal",
        tracker: "Job Tracker",
        technicians: "Technicians",
        services: "Service Catalog",
        subscription: "Subscription",
        messages: "Messages",
        reviews: "Reviews",
        settings: "Business Settings",
        verified_shop: "Verified Shop",
        total_revenue: "Total Revenue",
        active_jobs: "Active Jobs",
        completion_rate: "Completion Rate",
        search_placeholder: "Search anything...",
        logout: "Logout",
        partner_login: "Partner Login",
        join_network: "Join Network",
        hero_badge: "Ethiopia's #1 Roadside Network",
        hero_title_part1: "Grow your Garage with",
        hero_title_part2: "RoadHero Partner.",
        hero_desc: "Join thousands of verified service providers across Addis Ababa. Get more jobs, manage your technicians, and track your revenue in one premium portal.",
        recent_activity: "Recent Activity",
        job_history: "Job History",
        history: "History",
        help: "Help",
        welcome_back: "Welcome back",
        last_7_days: "Last 7 Days",
        view_all: "View All",
        revenue_analysis: "Transaction history & analysis",
        total_jobs: "Total Jobs",
        growth: "Growth",
        all: "All",
        app_requests: "App Requests",
        walk_ins: "Walk-ins",
        search_job_id: "Search Job ID or Hero...",
        date: "Date",
        time: "Time",
        source: "Source",
        service: "Service",
        technician: "Technician",
        amount_etb: "Amount (ETB)",
        showing_records: "Showing {count} of {total} records",
        add_job_entry: "Add Job Entry",
        configure_profile: "Configure your garage profile",
        garage_gallery: "Garage Photo Gallery",
        showcase_shop: "Showcase your shop and team",
        security_login: "Security & Login",
        notifications: "Notifications",
        queue_subtitle: "Real-time rescue tracking",
        search_queue_placeholder: "Search for Service Type or Vehicle...",
        active_requests: "Active Requests",
        gps_tracking: "GPS: Active Tracking",
        decline: "Decline",
        accept_request: "Accept Request",
        tracker_subtitle: "Live service mission control",
        signal_strong: "Signal: Strong (4G)",
        signal: "Signal",
        technician_speed: "Technician Speed",
        eta: "ETA",
        update_status: "Update Status",
        mission_completed: "Mission Completed",
        accepted: "Accepted",
        en_route: "En Route",
        arrived: "Arrived",
        working: "Working",
        urgent: "Urgent",
        nearby: "Nearby",
        catalog_subtitle: "Configure your offerings",
        add_custom: "+ Add Custom",
        catalog_description: "Define the menu of services visible to customers and set estimated pricing.",
        search_services: "Search services...",
        active_status: "Active Status",
        base_rate: "Base Rate (Est.)",
        editable: "Editable",
        technicians_subtitle: "Manage your team of experts",
        search_hero: "Search Hero name or phone...",
        hero_info: "Hero Info",
        hire_new_hero: "Hire New Hero",
        add_new_hero: "Add New Hero",
        new_team_member: "New team member",
        hero_photo: "Hero Photo",
        full_name: "Full Name",
        phone_number: "Phone Number",
        assigned_vehicle: "Assigned Vehicle",
        save_hero_profile: "Save Hero Profile",
        on_duty: "On Duty",
        offline: "Offline",
        towing: "Towing",
        electrician: "Electrician",
        mechanic: "Mechanic",
        reviews_subtitle: "Reputation management & feedback",
        online_for_requests: "Online for Requests",
        overall_reputation: "Overall Reputation",
        based_on_reviews: "Based on {count} reviews",
        response_velocity: "Response Velocity",
        high_speed: "High Speed",
        industry_leading: "Industry leading resolution speed",
        total_interactions: "Total Interactions",
        dynamic_feedback: "+{count} dynamic feedback this week",
        customer_insights: "Recent Customer Insights",
        critical_delay: "Critical Delay",
        reply_to_review: "Reply to Review",
        resolve_issue: "Resolve Issue",
        reputation_note: "Your average rating affects your visibility on the customer map. High-rated garages are prioritized.",
        history_subtitle: "Archive of all completed rescues",
        search_job_customer: "Search Job ID or Customer...",
        export: "Export",
        job_id: "Job ID",
        customer: "Customer",
        actions: "Actions",
        success: "SUCCESS",
        cancelled: "CANCELLED",
        total: "Total",
        notification_settings: "Detailed Notifications",
        push_notifications: "Push Notifications",
        email_alerts: "Email Alerts",
        sms_alerts: "SMS Alerts",
        new_request_alert: "New Request Alert",
        new_request_desc: "Get notified immediately for new rescue requests.",
        payment_confirmation: "Payment Confirmation",
        payment_desc: "Receive alerts for incoming payments and settlements.",
        system_updates: "System Updates",
        system_desc: "Important notices about portal maintenance and features.",
        marketing_emails: "Marketing & Tips",
        marketing_desc: "Growth tips and occasional marketing updates.",
        sound_alerts: "Audio Alerts",
        sound_desc: "Play a sound for critical events.",
        save_preferences: "Save Preferences",
    },
    am: {
        dashboard: "ዳሽቦርድ",
        queue: "የጥያቄ ወረፋ",
        revenue: "የገቢ መዝገብ",
        tracker: "የስራ መከታተያ",
        technicians: "ባለሙያዎች",
        services: "የአገልግሎት ዝርዝር",
        subscription: "ምዝገባ",
        messages: "መልእክቶች",
        reviews: "ግምገማዎች",
        settings: "የንግድ ቅንብሮች",
        verified_shop: "የተረጋገጠ ሱቅ",
        total_revenue: "ጠቅላላ ገቢ",
        active_jobs: "ንቁ ስራዎች",
        completion_rate: "የማጠናቀቂያ መጠን",
        search_placeholder: "ፈልግ...",
        logout: "ውጣ",
        partner_login: "የአጋር ይግቡ",
        join_network: "መረቡን ይቀላቀሉ",
        hero_badge: "የኢትዮጵያ #1 የመንገድ ዳር አገልግሎት",
        hero_title_part1: "ጋራዥዎን በ",
        hero_title_part2: "ሮድሂሮ አጋር ያሳድጉ።",
        hero_desc: "በአዲስ አበባ ውስጥ በሺዎች የሚቆጠሩ የተረጋገጡ የአገልግሎት ሰጪዎችን ይቀላቀሉ። ተጨማሪ ስራዎችን ያግኙ፣ ባለሙያዎቻችሁን ያስተዳድሩ እና ገቢዎን በአንድ ፕሪሚየም ፖርታል ይከታተሉ።",
        recent_activity: "የቅርብ ጊዜ እንቅስቃሴ",
        job_history: "የስራ ታሪክ",
        history: "ታሪክ",
        help: "እርዳታ",
        welcome_back: "እንኳን ደህና መጡ",
        last_7_days: "ባለፉት 7 ቀናት",
        view_all: "ሁሉንም ይመልከቱ",
        revenue_analysis: "የግብይት ታሪክ እና ትንተና",
        total_jobs: "ጠቅላላ ስራዎች",
        growth: "እድገት",
        all: "ሁሉም",
        app_requests: "የመተግበሪያ ጥያቄዎች",
        walk_ins: "በአካል የመጡ",
        search_job_id: "የስራ መታወቂያ ወይም ጀግና ፈልግ...",
        date: "ቀን",
        time: "ሰዓት",
        source: "ምንጭ",
        service: "አገልግሎት",
        technician: "ባለሙያ",
        amount_etb: "መጠን (ETB)",
        showing_records: "ከ {total} ውስጥ {count} ያሳያል",
        add_job_entry: "የስራ ግቤት ያክሉ",
        configure_profile: "የጋራዥ መገለጫዎን ያዋቅሩ",
        garage_gallery: "የጋራዥ ፎቶ ማዕከለ-ስዕላት",
        showcase_shop: "ሱቅዎን እና ቡድንዎን ያሳዩ",
        security_login: "ደህንነት እና መግቢያ",
        notifications: "ማሳወቂያዎች",
        queue_subtitle: "የቀጥታ አድን ክትትል",
        search_queue_placeholder: "የአገልግሎት ዓይነት ወይም ተሽከርካሪ ይፈልጉ...",
        active_requests: "ንቁ ጥያቄዎች",
        gps_tracking: "GPS: የቀጥታ ክትትል",
        decline: "አትቀበል",
        accept_request: "ተቀበል",
        tracker_subtitle: "የቀጥታ አገልግሎት ቁጥጥር",
        signal_strong: "ሲግናል: ጠንካራ (4G)",
        signal: "ሲግናል",
        technician_speed: "የባለሙያ ፍጥነት",
        eta: "መድረሻ ሰዓት",
        update_status: "ሁኔታውን አዘምን",
        mission_completed: "ስራው ተጠናቋል",
        accepted: "ተቀባይነት አግኝቷል",
        en_route: "በመንገድ ላይ",
        arrived: "ደርሷል",
        working: "ሥራ ላይ",
        urgent: "አስቸኳይ",
        nearby: "ቅርብ",
        catalog_subtitle: "ቅናሾችዎን ያዋቅሩ",
        add_custom: "+ ብጁ ያክሉ",
        catalog_description: "ለደንበኞች የሚታዩ የአገልግሎቶችን ዝርዝር ይግለጹ እና ግምታዊ ዋጋ ያስቀምጡ።",
        search_services: "አገልግሎቶችን ይፈልጉ...",
        active_status: "ንቁ ሁኔታ",
        base_rate: "መሠረታዊ ተመን (ግምት)",
        editable: "ሊስተካከል የሚችል",
        technicians_subtitle: "የባለሙያ ቡድንዎን ያስተዳድሩ",
        search_hero: "የጀግና ስም ወይም ስልክ ፈልግ...",
        hero_info: "የጀግና መረጃ",
        hire_new_hero: "አዲስ ጀግና ቅጠር",
        add_new_hero: "አዲስ ጀግና ያክሉ",
        new_team_member: "አዲስ የቡድን አባል",
        hero_photo: "የጀግና ፎቶ",
        full_name: "ሙሉ ስም",
        phone_number: "ስልክ ቁጥር",
        assigned_vehicle: "የተመደበ ተሽከርካሪ",
        save_hero_profile: "የጀግና መገለጫን አስቀምጥ",
        on_duty: "ሥራ ላይ",
        offline: "ከመስመር ውጭ",
        towing: "ጎትቶ መውሰድ",
        electrician: "ኤሌክትሪሻን",
        mechanic: "ሜካኒክ",
        reviews_subtitle: "የስም አስተዳደር እና ግብረመልስ",
        online_for_requests: "ለጥያቄዎች መስመር ላይ",
        overall_reputation: "አጠቃላይ ዝና",
        based_on_reviews: "በ {count} ግምገማዎች ላይ የተመሠረተ",
        response_velocity: "የምላሽ ፍጥነት",
        high_speed: "ከፍተኛ ፍጥነት",
        industry_leading: "በኢንዱስትሪው ውስጥ ቀዳሚ የጥራት ደረጃ",
        total_interactions: "ጠቅላላ ግንኙነቶች",
        dynamic_feedback: "+{count} ተለዋዋጭ ግብረመልስ በዚህ ሳምንት",
        customer_insights: "የቅርብ ጊዜ የደንበኛ ግንዛቤዎች",
        critical_delay: "ከባድ መዘግየት",
        reply_to_review: "ለግምገማው ምላሽ ይስጡ",
        resolve_issue: "ችግሩን ይፍቱ",
        reputation_note: "የእርስዎ አማካይ ደረጃ በደንበኛው ካርታ ላይ ያለዎትን ታይነት ይነካል። ከፍተኛ ደረጃ ያላቸው ጋራዦች ቅድሚያ ይሰጣቸዋል።",
        history_subtitle: "የሁሉም የተጠናቀቁ ስራዎች መዝገብ",
        search_job_customer: "የስራ መታወቂያ ወይም ደንበኛ ይፈልጉ...",
        export: "ላክ (Export)",
        job_id: "የስራ መታወቂያ",
        customer: "ደንበኛ",
        actions: "እርምጃዎች",
        success: "ተሳክቷል",
        cancelled: "ተሰርዟል",
        total: "ጠቅላላ",
        notification_settings: "ዝርዝር ማሳወቂያዎች",
        push_notifications: "የፑሽ ማሳወቂያዎች",
        email_alerts: "የኢሜይል ማንቂያዎች",
        sms_alerts: "የኤስኤምኤስ ማንቂያዎች",
        new_request_alert: "የአዲስ ጥያቄ ማንቂያ",
        new_request_desc: "ለአዳዲስ የማዳን ጥያቄዎች ወዲያውኑ ማሳወቂያ ያግኙ።",
        payment_confirmation: "የክፍያ ማረጋገጫ",
        payment_desc: "ለገቢ ክፍያዎች እና ስምምነቶች ማንቂያዎችን ይቀበሉ።",
        system_updates: "የስርዓት ዝመናዎች",
        system_desc: "ስለ ፖርታል ጥገና እና ባህሪያት አስፈላጊ ማሳሰቢያዎች።",
        marketing_emails: "ግብይት እና ምክሮች",
        marketing_desc: "የእድገት ምክሮች እና አልፎ አልፎ የግብይት ዝመናዎች።",
        sound_alerts: "የድምፅ ማንቂያዎች",
        sound_desc: "ለአስፈላጊ ክስተቶች ድምፅ ያጫውቱ።",
        save_preferences: "ምርጫዎችን አስቀምጥ",
    }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider = ({ children }: { children: React.ReactNode }) => {
    const [language, setLanguage] = useState<Language>('en');

    const t = (key: string) => {
        return translations[language][key] || key;
    };

    return (
        <LanguageContext.Provider value={{ language, setLanguage, t }}>
            {children}
        </LanguageContext.Provider>
    );
};

export const useLanguage = () => {
    const context = useContext(LanguageContext);
    if (!context) {
        throw new Error('useLanguage must be used within a LanguageProvider');
    }
    return context;
};
