"use client";

import React, { createContext, useContext, useState, useEffect } from 'react';

type Language = 'en' | 'am';

interface LanguageContextType {
    language: Language;
    setLanguage: (lang: Language) => void;
    t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
    en: {
        dashboard: "Dashboard",
        queue: "Request Queue",
        revenue: "Revenue Journal",
        tracker: "Job Tracker",
        technicians: "Technicians",
        services: "Service Catalog",
        subscription: "Subscription",
        messages: "Messages",
        reviews: "Reviews",
        settings: "Business Settings",
        verified_shop: "Verified Shop",
        total_revenue: "Total Revenue",
        active_jobs: "Active Jobs",
        pending_requests: "Pending Requests",
        monthly_jobs: "Monthly Jobs",
        completion_rate: "Completion Rate",
        search_placeholder: "Search anything...",
        logout: "Logout",
        partner_login: "Partner Login",
        join_network: "Join Network",
        hero_badge: "Ethiopia's #1 Roadside Network",
        hero_title_part1: "Grow your Garage with",
        hero_title_part2: "RoadHero Partner.",
        hero_desc: "Join thousands of verified service providers across Addis Ababa. Get more jobs, manage your technicians, and track your revenue in one premium portal.",
        recent_activity: "Recent Activity",
        job_history: "Job History",
        history: "History",
        help: "Help",
        welcome_back: "Welcome back",
        last_7_days: "Last 7 Days",
        view_all: "View All",
        revenue_analysis: "Transaction history & analysis",
        total_jobs: "Total Jobs",
        growth: "Growth",
        all: "All",
        app_requests: "App Requests",
        walk_ins: "Walk-ins",
        search_job_id: "Search Job ID or Hero...",
        date: "Date",
        time: "Time",
        source: "Source",
        service: "Service",
        technician: "Technician",
        amount_etb: "Amount (ETB)",
        showing_records: "Showing {count} of {total} records",
        add_job_entry: "Add Job Entry",
        configure_profile: "Configure your garage profile",
        garage_gallery: "Garage Photo Gallery",
        showcase_shop: "Showcase your shop and team",
        security_login: "Security & Login",
        notifications: "Notifications",
        queue_subtitle: "Real-time rescue tracking",
        search_queue_placeholder: "Search for Service Type or Vehicle...",
        active_requests: "Active Requests",
        gps_tracking: "GPS: Active Tracking",
        decline: "Decline",
        accept_request: "Accept Request",
        tracker_subtitle: "Live service mission control",
        signal_strong: "Signal: Strong (4G)",
        signal: "Signal",
        technician_speed: "Technician Speed",
        eta: "ETA",
        update_status: "Update Status",
        mission_completed: "Mission Completed",
        accepted: "Accepted",
        en_route: "En Route",
        arrived: "Arrived",
        working: "Working",
        urgent: "Urgent",
        nearby: "Nearby",
        catalog_subtitle: "Configure your offerings",
        add_custom: "+ Add Custom",
        catalog_description: "Define the menu of services visible to customers and set estimated pricing.",
        search_services: "Search services...",
        active_status: "Active Status",
        base_rate: "Base Rate (Est.)",
        editable: "Editable",
        click_to_edit: "Click to edit",
        save_service: "Save Service",
        update_service: "Update Service",
        technicians_subtitle: "Manage your team of experts",
        search_hero: "Search Hero name or phone...",
        hero_info: "Hero Info",
        hire_new_hero: "Hire New Hero",
        add_new_hero: "Add New Hero",
        new_team_member: "New team member",
        hero_photo: "Hero Photo",
        full_name: "Full Name",
        phone_number: "Phone Number",
        assigned_vehicle: "Assigned Vehicle",
        save_hero_profile: "Save Hero Profile",
        on_duty: "On Duty",
        offline: "Offline",
        towing: "Towing",
        electrician: "Electrician",
        mechanic: "Mechanic",
        reviews_subtitle: "Reputation management & feedback",
        online_for_requests: "Online for Requests",
        overall_reputation: "Overall Reputation",
        based_on_reviews: "Based on {count} reviews",
        response_velocity: "Response Velocity",
        high_speed: "High Speed",
        industry_leading: "Industry leading resolution speed",
        total_interactions: "Total Interactions",
        dynamic_feedback: "+{count} dynamic feedback this week",
        customer_insights: "Recent Customer Insights",
        critical_delay: "Critical Delay",
        reply_to_review: "Reply to Review",
        resolve_issue: "Resolve Issue",
        reputation_note: "Your average rating affects your visibility on the customer map. High-rated garages are prioritized.",
        history_subtitle: "Archive of all completed rescues",
        search_job_customer: "Search Job ID or Customer...",
        export: "Export",
        job_id: "Job ID",
        customer: "Customer",
        actions: "Actions",
        success: "SUCCESS",
        cancelled: "CANCELLED",
        total: "Total",
        notification_settings: "Detailed Notifications",
        push_notifications: "Push Notifications",
        email_alerts: "Email Alerts",
        sms_alerts: "SMS Alerts",
        new_request_alert: "New Request Alert",
        new_request_desc: "Get notified immediately for new rescue requests.",
        payment_confirmation: "Payment Confirmation",
        payment_desc: "Receive alerts for incoming payments and settlements.",
        system_updates: "System Updates",
        system_desc: "Important notices about portal maintenance and features.",
        marketing_emails: "Marketing & Tips",
        marketing_desc: "Growth tips and occasional marketing updates.",
        sound_alerts: "Audio Alerts",
        sound_desc: "Play a sound for critical events.",
        save_preferences: "Save Preferences",
        inventory: "Inventory",
        inventory_subtitle: "Manage spare parts & stock",
        search_inventory: "Search by part name or description...",
        add_part: "Add Spare Part",
        low_stock: "Low Stock",
        in_stock: "In Stock",
        part_details: "Part Details",
        stock_level: "Stock Level",
        units_left: "units left",
        deduct_stock: "Deduct Stock",
        remove_from_warehouse: "Remove from warehouse",
        quantity_to_remove: "Quantity to Remove",
        confirm_deduction: "Confirm Deduction",
        finalize_mission: "Finalize Mission",
        complete_service_payment: "Complete service & payment",
        total_collected_etb: "Total Amount Collected (ETB)",
        payment_method_label: "Payment Method",
        internal_notes: "Internal Notes",
        finalize_job: "Finalize Job",
        all_clear: "All Clear!",
        no_active_missions: "You have no active missions at the moment. Check the Job Queue for new requests.",
        view_job_queue: "View Job Queue",
        connecting_missions: "Connecting to active missions...",
        distance: "Distance",
        support_center: "Support Center",
        how_can_we_help: "How can we help?",
        support_desc: "Search our help documentation or get in touch with our 24/7 dedicated partner support team.",
        search_help: "Search help articles...",
        call_hotline: "Call Partner Hotline",
        priority_support: "24/7 Priority Support",
        email_support: "Email Support",
        response_time: "Response < 4 hours",
        in_app_message: "In-App Message",
        open_chat: "Open Support Chat",
        realtime_assistance: "Real-time Assistance",
        faqs: "Frequently Asked Questions",
        partnership_agreement: "Partnership Agreement",
        terms_of_service: "Terms of Service",
        terms_desc: "By using the RoadHero Partner Portal, you agree to comply with the following terms and conditions. Please read them carefully.",
        quality: "Quality",
        identity: "Identity",
        compliance: "Compliance",
        quality_desc: "Maintain high service standards for all rescues.",
        identity_desc: "Provide accurate and verified business credentials.",
        compliance_desc: "Adhere to local laws and RoadHero safety guidelines.",
        provider_eligibility: "1. Provider Eligibility",
        eligibility_text: "To become a RoadHero Service Provider, you must possess a valid business license for automotive services in Ethiopia. You are responsible for ensuring all staff performing rescues are properly trained and insured.",
        service_standards: "2. Service Standards",
        standards_text: "Providers agree to respond to accepted rescue requests promptly. Professional conduct is required at all times when interacting with RoadHero customers. Failure to maintain a high rating may lead to account suspension.",
        payments_fees: "3. Payments & Fees",
        payments_text: "RoadHero facilitates payments between customers and providers. A platform service fee is deducted from each successful transaction. Details of current fee structures are available in the provider dashboard.",
        important_notice: "Important Notice",
        notice_text: "RoadHero is a platform connecting customers with independent service providers. We do not employ providers and are not responsible for the quality of individual mechanical repairs.",
        legal_privacy: "Legal & Privacy",
        privacy_policy: "Privacy Policy",
        privacy_policy_desc: "Your privacy is our priority. This policy outlines how we collect, use, and protect your personal information within the RoadHero Partner Portal.",
        info_collection: "Information Collection",
        profile_data: "Profile Data",
        profile_data_desc: "We collect your name, phone number, and business details to create and verify your service provider account.",
        location_data: "Location Data",
        location_data_desc: "Precise GPS coordinates of your business are collected to connect you with drivers in need of assistance.",
        how_we_use_data: "How We Use Your Data",
        data_security: "Data Security",
        security_text: "RoadHero employs industry-standard encryption protocols (SSL/TLS) for data transmission and multi-layered security for data storage. Access to your personal information is restricted to authorized personnel who require it for operational purposes.",
        data_sharing_text: "We do not sell, trade, or otherwise transfer your personally identifiable information to outside parties.",
        use_data_item1: "Facilitating rescue requests and service management",
        use_data_item2: "Verifying business credentials and professional identity",
        use_data_item3: "Processing payments and generating financial reports",
        use_data_item4: "Improving the platform through anonymous usage analytics",
        use_data_item5: "Communicating critical system updates and support info",
        faq_q1: "How long does verification take?",
        faq_a1: "Typically 24-48 business hours once all documents are submitted and the orientation call is complete.",
        faq_q2: "What equipment do I need?",
        faq_a2: "Providers must have at least one functional rescue vehicle (tow truck or service van) and standard repair tools.",
        faq_q3: "How am I paid?",
        faq_a3: "Payments are processed instantly through Telebirr or bank transfer once a rescue mission is marked as complete.",
        faq_q4: "Can I choose my service area?",
        faq_a4: "Yes, you can define your operational radius within the provider settings dashboard.",
        join_network_title: "Join the Network",
        join_network_desc: "Register your garage or towing service today.",
        already_partner: "Already a partner?",
        login_here: "Login here",
        feature_verification_title: "Provider Verification",
        feature_verification_desc: "Trusted by drivers. Every partner undergoes a rigorous document verification process.",
        feature_leads_title: "Lead Management",
        feature_leads_desc: "Get instant alerts for rescue requests near your location. Manage your queue effortlessly.",
        feature_revenue_title: "Revenue Tracking",
        feature_revenue_desc: "Built-in Revenue Journal to track app income and manual walk-ins for your business.",
        footer_rights: "© 2026 RoadHero Technologies. All rights reserved.",
        footer_mission: "Empowering garage owners with premium management tools.",
        footer_links: "Quick Links",
        footer_support: "Support",
        footer_contact: "Contact Us",
        feature_tracker_title: "Real-time Tracking",
        feature_tracker_desc: "Live GPS monitoring of your technicians and service requests.",
        feature_technicians_title: "Staff Management",
        feature_technicians_desc: "Manage your team, track performance, and assign vehicles.",
        feature_services_title: "Custom Catalog",
        feature_services_desc: "Define your own services and set your own rates.",
        registration_title: "Partner Registration",
        registration_subtitle: "Join thousands of service providers expanding their reach with RoadHero.",
        step_profile: "Profile",
        step_business: "Business",
        step_location: "Location",
        step_verify: "Verify",
        full_name_label: "Full Name",
        full_name_placeholder: "Abebe Bikila",
        email_label: "Personal Email",
        email_placeholder: "abebe@example.com",
        phone_label: "Phone Number",
        phone_placeholder: "+251922334455",
        password_label: "Create Password",
        confirm_password_label: "Confirm Password",
        business_details: "Business Details",
        business_name_label: "Business Name",
        business_name_placeholder: "Abyssinia Motors",
        service_category_label: "Service Category",
        tin_number_label: "TIN Number",
        tin_number_placeholder: "0045623XXX",
        shop_location: "Shop Location",
        search_landmark: "Search Landmark",
        search_landmark_placeholder: "Bole, Addis Ababa",
        spatial_accuracy: "Spatial Accuracy",
        lat_label: "LAT",
        lng_label: "LNG",
        directions_note_label: "Directions Note",
        directions_note_placeholder: "e.g. Behind Dembel City Center, Gate 2.",
        verify_business_title: "Verify Business",
        verify_business_desc: "Document upload for partner identity verification.",
        business_license_label: "Business License",
        tin_certificate_label: "TIN Certificate",
        owner_id_label: "Owner Identity",
        national_id_passport: "National ID / Passport",
        kebele_id_passport: "Kebele ID or Passport",
        select_file: "Select PDF/IMG",
        max_size: "Max. 5MB",
        tax_certificate: "Tax Certificate",
        required_doc: "Required Doc",
        back: "Back",
        next_step: "Next Step",
        complete_registration: "Complete Registration",
        partner_portal_version: "Partner Portal v1.0",
        step_indicator: "Step {current} of 4 — Business Partner Verification",
    },
    am: {
        dashboard: "ዳሽቦርድ",
        queue: "የጥያቄ ወረፋ",
        revenue: "የገቢ መዝገብ",
        tracker: "የስራ መከታተያ",
        technicians: "ባለሙያዎች",
        services: "የአገልግሎት ዝርዝር",
        subscription: "ምዝገባ",
        messages: "መልእክቶች",
        reviews: "ግምገማዎች",
        settings: "የንግድ ቅንብሮች",
        verified_shop: "የተረጋገጠ ሱቅ",
        total_revenue: "ጠቅላላ ገቢ",
        active_jobs: "ንቁ ስራዎች",
        pending_requests: "በመጠባበቅ ላይ ያሉ ጥያቄዎች",
        monthly_jobs: "የወር ስራዎች",
        completion_rate: "የማጠናቀቂያ መጠን",
        search_placeholder: "ፈልግ...",
        logout: "ውጣ",
        partner_login: "የአጋር ይግቡ",
        join_network: "መረቡን ይቀላቀሉ",
        hero_badge: "የኢትዮጵያ #1 የመንገድ ዳር አገልግሎት",
        hero_title_part1: "ጋራዥዎን በ",
        hero_title_part2: "ሮድሂሮ አጋር ያሳድጉ።",
        hero_desc: "በአዲስ አበባ ውስጥ በሺዎች የሚቆጠሩ የተረጋገጡ የአገልግሎት ሰጪዎችን ይቀላቀሉ። ተጨማሪ ስራዎችን ያግኙ፣ ባለሙያዎቻችሁን ያስተዳድሩ እና ገቢዎን በአንድ ፕሪሚየም ፖርታል ይከታተሉ።",
        recent_activity: "የቅርብ ጊዜ እንቅስቃሴ",
        job_history: "የስራ ታሪክ",
        history: "ታሪክ",
        help: "እርዳታ",
        welcome_back: "እንኳን ደህና መጡ",
        last_7_days: "ባለፉት 7 ቀናት",
        view_all: "ሁሉንም ይመልከቱ",
        revenue_analysis: "የግብይት ታሪክ እና ትንተና",
        total_jobs: "ጠቅላላ ስራዎች",
        growth: "እድገት",
        all: "ሁሉም",
        app_requests: "የመተግበሪያ ጥያቄዎች",
        walk_ins: "በአካል የመጡ",
        search_job_id: "የስራ መታወቂያ ወይም ጀግና ፈልግ...",
        date: "ቀን",
        time: "ሰዓት",
        source: "ምንጭ",
        service: "አገልግሎት",
        technician: "ባለሙያ",
        amount_etb: "መጠን (ETB)",
        showing_records: "ከ {total} ውስጥ {count} ያሳያል",
        add_job_entry: "የስራ ግቤት ያክሉ",
        configure_profile: "የጋራዥ መገለጫዎን ያዋቅሩ",
        garage_gallery: "የጋራዥ ፎቶ ማዕከለ-ስዕላት",
        showcase_shop: "ሱቅዎን እና ቡድንዎን ያሳዩ",
        security_login: "ደህንነት እና መግቢያ",
        notifications: "ማሳወቂያዎች",
        queue_subtitle: "የቀጥታ አድን ክትትል",
        search_queue_placeholder: "የአገልግሎት ዓይነት ወይም ተሽከርካሪ ይፈልጉ...",
        active_requests: "ንቁ ጥያቄዎች",
        gps_tracking: "GPS: የቀጥታ ክትትል",
        decline: "አትቀበል",
        accept_request: "ተቀበል",
        tracker_subtitle: "የቀጥታ አገልግሎት ቁጥጥር",
        signal_strong: "ሲግናል: ጠንካራ (4G)",
        signal: "ሲግናል",
        technician_speed: "የባለሙያ ፍጥነት",
        eta: "መድረሻ ሰዓት",
        update_status: "ሁኔታውን አዘምን",
        mission_completed: "ስራው ተጠናቋል",
        accepted: "ተቀባይነት አግኝቷል",
        en_route: "በመንገድ ላይ",
        arrived: "ደርሷል",
        working: "ሥራ ላይ",
        urgent: "አስቸኳይ",
        nearby: "ቅርብ",
        catalog_subtitle: "ቅናሾችዎን ያዋቅሩ",
        add_custom: "+ ብጁ ያክሉ",
        catalog_description: "ለደንበኞች የሚታዩ የአገልግሎቶችን ዝርዝር ይግለጹ እና ግምታዊ ዋጋ ያስቀምጡ።",
        search_services: "አገልግሎቶችን ይፈልጉ...",
        active_status: "ንቁ ሁኔታ",
        base_rate: "መሠረታዊ ተመን (ግምት)",
        editable: "ሊስተካከል የሚችል",
        click_to_edit: "ለማረም ጠቅ ያድርጉ",
        save_service: "አገልግሎቱን አስቀምጥ",
        update_service: "አገልግሎቱን አዘምን",
        technicians_subtitle: "የባለሙያ ቡድንዎን ያስተዳድሩ",
        search_hero: "የጀግና ስም ወይም ስልክ ፈልግ...",
        hero_info: "የጀግና መረጃ",
        hire_new_hero: "አዲስ ጀግና ቅጠር",
        add_new_hero: "አዲስ ጀግና ያክሉ",
        new_team_member: "አዲስ የቡድን አባል",
        hero_photo: "የጀግና ፎቶ",
        full_name: "ሙሉ ስም",
        phone_number: "ስልክ ቁጥር",
        assigned_vehicle: "የተመደበ ተሽከርካሪ",
        save_hero_profile: "የጀግና መገለጫን አስቀምጥ",
        on_duty: "ሥራ ላይ",
        offline: "ከመስመር ውጭ",
        towing: "ጎትቶ መውሰድ",
        electrician: "ኤሌክትሪሻን",
        mechanic: "ሜካኒክ",
        reviews_subtitle: "የስም አስተዳደር እና ግብረመልስ",
        online_for_requests: "ለጥያቄዎች መስመር ላይ",
        overall_reputation: "አጠቃላይ ዝና",
        based_on_reviews: "በ {count} ግምገማዎች ላይ የተመሠረተ",
        response_velocity: "የምላሽ ፍጥነት",
        high_speed: "ከፍተኛ ፍጥነት",
        industry_leading: "በኢንዱስትሪው ውስጥ ቀዳሚ የጥራት ደረጃ",
        total_interactions: "ጠቅላላ ግንኙነቶች",
        dynamic_feedback: "+{count} ተለዋዋጭ ግብረመልስ በዚህ ሳምንት",
        customer_insights: "የቅርብ ጊዜ የደንበኛ ግንዛቤዎች",
        critical_delay: "ከባድ መዘግየት",
        reply_to_review: "ለግምገማው ምላሽ ይስጡ",
        resolve_issue: "ችግሩን ይፍቱ",
        reputation_note: "የእርስዎ አማካይ ደረጃ በደንበኛው ካርታ ላይ ያለዎትን ታይነት ይነካል። ከፍተኛ ደረጃ ያላቸው ጋራዦች ቅድሚያ ይሰጣቸዋል።",
        history_subtitle: "የሁሉም የተጠናቀቁ ስራዎች መዝገብ",
        search_job_customer: "የስራ መታወቂያ ወይም ደንበኛ ይፈልጉ...",
        export: "ላክ (Export)",
        job_id: "የስራ መታወቂያ",
        customer: "ደንበኛ",
        actions: "እርምጃዎች",
        success: "ተሳክቷል",
        cancelled: "ተሰርዟል",
        total: "ጠቅላላ",
        notification_settings: "ዝርዝር ማሳወቂያዎች",
        push_notifications: "የፑሽ ማሳወቂያዎች",
        email_alerts: "የኢሜይል ማንቂያዎች",
        sms_alerts: "የኤስኤምኤስ ማንቂያዎች",
        new_request_alert: "የአዲስ ጥያቄ ማንቂያ",
        new_request_desc: "ለአዳዲስ የማዳን ጥያቄዎች ወዲያውኑ ማሳወቂያ ያግኙ።",
        payment_confirmation: "የክፍያ ማረጋገጫ",
        payment_desc: "ለገቢ ክፍያዎች እና ስምምነቶች ማንቂያዎችን ይቀበሉ።",
        system_updates: "የስርዓት ዝመናዎች",
        system_desc: "ስለ ፖርታል ጥገና እና ባህሪያት አስፈላጊ ማሳሰቢያዎች።",
        marketing_emails: "ግብይት እና ምክሮች",
        marketing_desc: "የእድገት ምክሮች እና አልፎ አልፎ የግብይት ዝመናዎች።",
        sound_alerts: "የድምፅ ማንቂያዎች",
        sound_desc: "ለአስፈላጊ ክስተቶች ድምፅ ያጫውቱ።",
        save_preferences: "ምርጫዎችን አስቀምጥ",
        inventory: "ኢንቬንቶሪ",
        inventory_subtitle: "የመለዋወጫ ዕቃዎችን እና ክምችትን ያስተዳድሩ",
        search_inventory: "በስም ወይም በዝርዝር ይፈልጉ...",
        add_part: "መለዋወጫ ያክሉ",
        low_stock: "ዝቅተኛ ክምችት",
        in_stock: "በክምችት ላይ ያለ",
        part_details: "የመለዋወጫ ዝርዝር",
        stock_level: "የክምችት መጠን",
        units_left: "የቀሩ ክፍሎች",
        deduct_stock: "ክምችት መቀነስ",
        remove_from_warehouse: "ከመጋዘን ቀንሱ",
        quantity_to_remove: "የሚቀነሰው መጠን",
        confirm_deduction: "መቀነሱን ያረጋግጡ",
        finalize_mission: "ስራውን ያጠናቅቁ",
        complete_service_payment: "አገልግሎቱን እና ክፍያውን ያጠናቅቁ",
        total_collected_etb: "ጠቅላላ የተሰበሰበ መጠን (ETB)",
        payment_method_label: "የክፍያ ዘዴ",
        internal_notes: "ውስጣዊ ማስታወሻዎች",
        finalize_job: "ስራውን ፍጸም",
        all_clear: "ሁሉም ተጠናቅቀዋል!",
        no_active_missions: "በአሁኑ ጊዜ ምንም ንቁ ስራዎች የሉዎትም። አዳዲስ ጥያቄዎችን ለማግኘት የጥያቄ ወረፋውን ይመልከቱ።",
        view_job_queue: "የጥያቄ ወረፋውን ይመልከቱ",
        connecting_missions: "ከንቁ ስራዎች ጋር በመገናኘት ላይ...",
        distance: "ርቀት",
        support_center: "የእርዳታ ማዕከል",
        how_can_we_help: "እንዴት ልንረዳዎ እንችላለን?",
        support_desc: "የእርዳታ ሰነዶቻችንን ይፈልጉ ወይም በቀን 24 ሰዓት በሳምንት 7 ቀን ዝግጁ ከሆነው የአጋር ድጋፍ ቡድናችን ጋር ይገናኙ።",
        search_help: "የእርዳታ ጽሁፎችን ይፈልጉ...",
        call_hotline: "የአጋር የስልክ መስመር ይደውሉ",
        priority_support: "24/7 ቅድሚያ የሚሰጠው እርዳታ",
        email_support: "በኢሜይል ድጋፍ",
        response_time: "ምላሽ < 4 ሰዓታት",
        in_app_message: "በመተግበሪያው ውስጥ መልእክት",
        open_chat: "የድጋፍ ቻቱን ይክፈቱ",
        realtime_assistance: "የቀጥታ እርዳታ",
        faqs: "ተደጋግመው የሚጠየቁ ጥያቄዎች",
        partnership_agreement: "የአጋርነት ስምምነት",
        terms_of_service: "የአገልግሎት ውሎች",
        terms_desc: "የሮድሂሮ አጋር ፖርታልን በመጠቀም፣ የሚከተሉትን ውሎች እና ሁኔታዎች ለማክበር ተስማምተዋል። እባክዎን በጥንቃቄ ያንብቡ።",
        quality: "ጥራት",
        identity: "ማንነት",
        compliance: "ተገዢነት",
        quality_desc: "ለሁሉም የማዳን ስራዎች ከፍተኛ የአገልግሎት ደረጃዎችን ይጠብቁ።",
        identity_desc: "ትክክለኛ እና የተረጋገጡ የንግድ ማስረጃዎችን ያቅርቡ።",
        compliance_desc: "የአካባቢ ህጎችን እና የሮድሂሮ የደህንነት መመሪያዎችን ያክብሩ።",
        provider_eligibility: "1. የአቅራቢ ብቁነት",
        eligibility_text: "የሮድሂሮ አገልግሎት ሰጪ ለመሆን በኢትዮጵያ ውስጥ የተሸከርካሪ አገልግሎት የሚሰጥ ህጋዊ የንግድ ፈቃድ ሊኖርዎት ይገባል። ስራዎችን የሚያከናውኑ ሰራተኞች በሙሉ በትክክል የሰለጠኑ እና የኢንሹራንስ ዋስትና ያላቸው መሆናቸውን የማረጋገጥ ኃላፊነት አለብዎት።",
        service_standards: "2. የአገልግሎት ደረጃዎች",
        standards_text: "አገልግሎት ሰጪዎች ተቀባይነት ያላቸውን የማዳን ጥያቄዎች በፍጥነት ለመመለስ ተስማምተዋል። ከሮድሂሮ ደንበኞች ጋር በሚገናኙበት ጊዜ ሁሉ ሙያዊ ስነ-ምግባር ያስፈልጋል። ከፍተኛ ደረጃን አለመጠበቅ መለያዎ እንዲታገድ ሊያደርግ ይችላል።",
        payments_fees: "3. ክፍያዎች እና ክፍያዎች",
        payments_text: "ሮድሂሮ በደንበኞች እና በአገልግሎት ሰጪዎች መካከል ክፍያዎችን ያመቻቻል። ከእያንዳንዱ ስኬታማ ግብይት ላይ የፕላትፎርም አገልግሎት ክፍያ ይቀንሳል። የአሁኑ የክፍያ ተመኖች ዝርዝር በአገልግሎት ሰጪው ዳሽቦርድ ላይ ይገኛል።",
        important_notice: "አስፈላጊ ማሳሰቢያ",
        notice_text: "ሮድሂሮ ደንበኞችን ከግል አገልግሎት ሰጪዎች ጋር የሚያገናኝ ፕላትፎርም ነው። እኛ አገልግሎት ሰጪዎችን አንቀጥርም እና ለግለሰብ ሜካኒካል ጥገና ጥራት ተጠያቂ አይደለንም።",
        legal_privacy: "ህጋዊ እና ግላዊነት",
        privacy_policy: "የግላዊነት ፖሊሲ",
        privacy_policy_desc: "የእርስዎ ግላዊነት ቅድሚያ የምንሰጠው ጉዳይ ነው። ይህ ፖሊሲ በሮድሂሮ አጋር ፖርታል ውስጥ የእርስዎን የግል መረጃ እንዴት እንደምንሰበስብ፣ እንደምንጠቀም እና እንደምንጠብቅ ያብራራል።",
        info_collection: "መረጃ መሰብሰብ",
        profile_data: "የመገለጫ መረጃ",
        profile_data_desc: "አገልግሎት ሰጪ መለያዎን ለመፍጠር እና ለማረጋገጥ የእርስዎን ስም፣ ስልክ ቁጥር እና የንግድ ዝርዝሮችን እንሰበስባለን።",
        location_data: "የአካባቢ መረጃ",
        location_data_desc: "እርዳታ ከሚፈልጉ አሽከርካሪዎች ጋር ለማገናኘት የንግድዎ ትክክለኛ የጂፒኤስ መጋጠሚያዎች ይሰበሰባሉ።",
        how_we_use_data: "መረጃዎን እንዴት እንደምንጠቀምበት",
        data_security: "የመረጃ ደህንነት",
        security_text: "ሮድሂሮ ለመረጃ ማስተላለፍ የኢንዱስትሪ ደረጃውን የጠበቀ የኢንክሪፕሽን ፕሮቶኮሎችን (SSL/TLS) እና ለመረጃ ማከማቻ ባለብዙ ንብርብር ደህንነትን ይጠቀማል። የእርስዎን የግል መረጃ የማግኘት መብት ለስራ ለሚፈልጉ የተፈቀደላቸው ሰራተኞች ብቻ የተገደበ ነው።",
        data_sharing_text: "የእርስዎን ግላዊ መረጃ ለውጭ ወገኖች አንሸጥም፣ አንለዋወጥም ወይም አናስተላልፍም።",
        use_data_item1: "የማዳን ጥያቄዎችን እና የአገልግሎት አስተዳደርን ማመቻቸት",
        use_data_item2: "የንግድ ማስረጃዎችን እና ሙያዊ ማንነትን ማረጋገጥ",
        use_data_item3: "ክፍያዎችን ማከናወን እና የፋይናንስ ሪፖርቶችን ማመንጨት",
        use_data_item4: "ስም ባልተጠቀሰ የአጠቃቀም ትንተና አማካኝነት ፕላትፎርሙን ማሻሻል",
        use_data_item5: "አስፈላጊ የስርዓት ዝመናዎችን እና የድጋፍ መረጃዎችን ማሳወቅ",
        faq_q1: "ማረጋገጫው ምን ያህል ጊዜ ይወስዳል?",
        faq_a1: "ሁሉም ሰነዶች ከገቡ እና የመግቢያ ጥሪው ከተጠናቀቀ በኋላ ብዙውን ጊዜ ከ24-48 የስራ ሰዓታት ይወስዳል።",
        faq_q2: "ምን ዓይነት መሣሪያዎች ያስፈልጉኛል?",
        faq_a2: "አገልግሎት ሰጪዎች ቢያንስ አንድ የሚሰራ የማዳኛ ተሽከርካሪ (ተጎታች መኪና ወይም የአገልግሎት ቫን) እና መደበኛ የጥገና መሣሪያዎች ሊኖራቸው ይገባል።",
        faq_q3: "እንዴት ነው የሚከፈለኝ?",
        faq_a3: "የማዳን ስራው እንደተጠናቀቀ ክፍያዎች ወዲያውኑ በቴሌብድር ወይም በባንክ ዝውውር ይፈጸማሉ።",
        faq_q4: "የአገልግሎት ክልሌን መምረጥ እችላለሁ?",
        faq_a4: "አዎ፣ በአቅራቢው ቅንብሮች ዳሽቦርድ ውስጥ የእርስዎን የክዋኔ ራዲየስ መወሰን ይችላሉ።",
        join_network_title: "አውታረ መረቡን ይቀላቀሉ",
        join_network_desc: "ጋራዥዎን ወይም የጎታች አገልግሎትዎን ዛሬ ያስመዝግቡ።",
        already_partner: "ቀድመው አጋር ነዎት?",
        login_here: "እዚህ ይግቡ",
        feature_verification_title: "የአቅራቢ ማረጋገጫ",
        feature_verification_desc: "በአሽከርካሪዎች የታመነ። እያንዳንዱ አጋር ጥብቅ የሰነድ ማረጋገጫ ሂደትን ያልፋል።",
        feature_leads_title: "የመሪነት አስተዳደር",
        feature_leads_desc: "በአካባቢዎ ላሉ የማዳን ጥያቄዎች ፈጣን ማንቂያዎችን ያግኙ። የጥያቄ ወረፋዎን በቀላሉ ያስተዳድሩ።",
        feature_revenue_title: "የገቢ ክትትል",
        feature_revenue_desc: "የመተግበሪያ ገቢን እና ለንግድዎ በእጅ የሚገቡ ገቢዎችን ለመከታተል አብሮ የተሰራ የገቢ መዝገብ።",
        footer_rights: "© 2026 ሮድሂሮ ቴክኖሎጂስ። መብቱ በህግ የተጠበቀ ነው።",
        footer_mission: "ለጋራዥ ባለቤቶች ፕሪሚየም የአመራር መሣሪያዎችን በማቅረብ ማብቃት።",
        footer_links: "ፈጣን አገናኞች",
        footer_support: "እርዳታ",
        footer_contact: "ያግኙን",
        feature_tracker_title: "የቀጥታ ክትትል",
        feature_tracker_desc: "የባለሙያዎችዎን እና የአገልግሎት ጥያቄዎችን የቀጥታ የጂፒኤስ ክትትል.",
        feature_technicians_title: "የሰራተኞች አስተዳደር",
        feature_technicians_desc: "ቡድንዎን ያስተዳድሩ፣ አፈጻጸምን ይከታተሉ እና ተሽከርካሪዎችን ይመድቡ።",
        feature_services_title: "ብጁ አገልግሎቶች",
        feature_services_desc: "የራስዎን አገልግሎቶች ይግለጹ እና የራስዎን ዋጋዎች ያስቀምጡ።",
        registration_title: "የአጋር ምዝገባ",
        registration_subtitle: "በሮድሂሮ ተደራሽነታቸውን እያሰፉ ያሉ በሺዎች የሚቆጠሩ አገልግሎት ሰጪዎችን ይቀላቀሉ።",
        step_profile: "መገለጫ",
        step_business: "ንግድ",
        step_location: "አካባቢ",
        step_verify: "አረጋግጥ",
        full_name_label: "ሙሉ ስም",
        full_name_placeholder: "አበበ ቢቂላ",
        email_label: "የግል ኢሜይል",
        email_placeholder: "abebe@example.com",
        phone_label: "የስልክ ቁጥር",
        phone_placeholder: "+251922334455",
        password_label: "የይለፍ ቃል ፍጠር",
        confirm_password_label: "የይለፍ ቃል አረጋግጥ",
        business_details: "የንግድ ዝርዝሮች",
        business_name_label: "የንግድ ስም",
        business_name_placeholder: "አቢሲኒያ ሞተርስ",
        service_category_label: "የአገልግሎት ዘርፍ",
        tin_number_label: "የቲን (TIN) ቁጥር",
        tin_number_placeholder: "0045623XXX",
        shop_location: "የሱቅ አካባቢ",
        search_landmark: "መለያ ቦታ ይፈልጉ",
        search_landmark_placeholder: "ቦሌ፣ አዲስ አበባ",
        spatial_accuracy: "የቦታ ትክክለኛነት",
        lat_label: "ኬክሮስ (LAT)",
        lng_label: "ኬንትሮስ (LNG)",
        directions_note_label: "የአቅጣጫ ማስታወሻ",
        directions_note_placeholder: "ምሳሌ: ከደምበል ሲቲ ሴንተር ጀርባ፣ በር 2።",
        verify_business_title: "ንግዱን ያረጋግጡ",
        verify_business_desc: "ለአጋር ማንነት ማረጋገጫ የሰነድ ሰቀላ።",
        business_license_label: "የንግድ ፈቃድ",
        tin_certificate_label: "የቲን ሰርተፍኬት",
        owner_id_label: "የባለቤቱ ማንነት",
        national_id_passport: "ብሔራዊ መታወቂያ / ፓስፖርት",
        kebele_id_passport: "የቀበሌ መታወቂያ ወይም ፓስፖርት",
        select_file: "PDF/IMG ይምረጡ",
        max_size: "ከፍተኛ መጠን 5MB",
        tax_certificate: "የግብር ሰርተፍኬት",
        required_doc: "አስፈላጊ ሰነድ",
        back: "ተመለስ",
        next_step: "ቀጣይ እርምጃ",
        complete_registration: "ምዝገባውን ያጠናቅቁ",
        partner_portal_version: "የአጋር ፖርታል v1.0",
        step_indicator: "እርምጃ {current} ከ 4 — የንግድ አጋር ማረጋገጫ",
    },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider = ({ children }: { children: React.ReactNode }) => {
    const [language, setLanguage] = useState<Language>('en');

    const t = (key: string) => {
        return translations[language][key] || key;
    };

    return (
        <LanguageContext.Provider value={{ language, setLanguage, t }}>
            {children}
        </LanguageContext.Provider>
    );
};

export const useLanguage = () => {
    const context = useContext(LanguageContext);
    if (!context) {
        throw new Error('useLanguage must be used within a LanguageProvider');
    }
    return context;
};
